[package]
name = "elma-lev-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
elma = { git = "https://github.com/jgouly/elma-rust", branch = "fix-lev" }
rand = { version = "0.8.5", features = ["small_rng"] }
